#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url= jdbc:mysql://localhost:3306/umc_test
#spring.datasource.username=root
#spring.datasource.password=zpzzgjdg@$^1
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.show-sql=true
#logging.level.org.hibernate.type.descriptor.sql=DEBUG
#
#logging.level.org.hibernate.SQL=DEBUG
#
#spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER
#
#jwt.secret = rutyweorituwyerotiuweyrtoiuweyrtoweiurtywoeighdfsojkghsdfgsdofiguwyertouw
#jwt.issuer = test
#jwt.expirationtime = 3600

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/umc
    username: root
    password: zpzzgjdg@$^1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  profiles:
    active: dev

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: DEBUG
    org.hibernate.SQL: DEBUG

jwt:
  secret: rutyweorituwyerotiuweyrtoiuweyrtoweiurtywoeighdfsojkghsdfgsdofiguwyertouw
  issuer: test
  expirationtime: 3600
